name: "Build & Fill Cache"
on:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Install nix
      uses: cachix/install-nix-action@v18
    - name: Setup Cache
      uses: cachix/cachix-action@v12
      with:
        name: nix-dabei
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Build kexec
      run: |
        nix build .#kexec --json \
        | jq -r '.[].outputs | to_entries[].value' \
        | nix run nixpkgs#cachix push nix-dabei

    - name: Show kexec size
      run: du -Lh  result/*

    - name: Build simple example system
      run: |
        nix build ./examples/simple#nixosConfigurations.web-01.config.system.build.toplevel --json \
        | jq -r '.[].outputs | to_entries[].value' \
        | nix run nixpkgs#cachix push nix-dabei
